apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-server
  template:
    metadata:
      labels:
        app: json-server
    spec:
      containers:
        - name: json-server
          image: oleksiisyzonov/http_server:IMAGE_TAG_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: json-server-service
spec:
  selector:
    app: json-server
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30333
  type: NodePort
